import { getSupabase } from '../../lib/supabase'
import { localDay } from '../../lib/day'
import {
	ACHIEVEMENTS,
	type AchievementDefinition,
	type DayStats,
	type StreakState,
	type XpEvent,
} from './rules'

type Row = Record<string, unknown>
type QueryResult<T> = { data: T | null; error: { message: string } | null }

interface Query extends PromiseLike<QueryResult<Row[]>> {
	select(columns?: string): Query
	eq(column: string, value: unknown): Query
	order(column: string, options?: Row): Query
	limit(count: number): Query
	maybeSingle(): PromiseLike<QueryResult<Row>>
}

interface Client {
	from(table: string): Query
}

const client = (): Client => getSupabase() as unknown as Client
const num = (value: unknown): number => (typeof value === 'number' && Number.isFinite(value) ? value : 0)
const str = (value: unknown): string | null => (typeof value === 'string' ? value : null)

export type GamificationSummary = {
	day: string
	today: DayStats & { xpEarned: number }
	streak: StreakState
	totalXp: number
	level: number
	unlocked: string[]
	recentDays: Array<{ day: string; focusSeconds: number; studySeconds: number }>
}

export const gamificationRepository = {
	async summary(userId: string): Promise<GamificationSummary> {
		const day = localDay()
		const [activity, streakRow, xpRow, achievements, recent] = await Promise.all([
			client().from('daily_activity').select('*').eq('user_id', userId).eq('day', day).maybeSingle(),
			client().from('user_streaks').select('*').eq('user_id', userId).maybeSingle(),
			client().from('user_xp').select('*').eq('user_id', userId).maybeSingle(),
			client().from('user_achievements').select('achievement_key').eq('user_id', userId).limit(50),
			client()
				.from('daily_activity')
				.select('day, focus_seconds, study_seconds')
				.eq('user_id', userId)
				.order('day', { ascending: false })
				.limit(14),
		])

		const a = activity.data ?? {}
		const s = streakRow.data ?? {}
		const x = xpRow.data ?? {}
		return {
			day,
			today: {
				studySeconds: num(a.study_seconds),
				focusSeconds: num(a.focus_seconds),
				lessonsCompleted: num(a.lessons_completed),
				questionsAnswered: num(a.questions_answered),
				tasksCompleted: num(a.tasks_completed),
				xpEarned: num(a.xp_earned),
			},
			streak: {
				current: num(s.current_streak),
				longest: num(s.longest_streak),
				lastActiveDay: str(s.last_active_day) ?? str(s.last_active_on),
			},
			totalXp: num(x.total_xp),
			level: num(x.level) || 1,
			unlocked: (achievements.data ?? [])
				.map((row) => str(row.achievement_key))
				.filter((key): key is string => key !== null),
			recentDays: (recent.data ?? []).map((row) => ({
				day: str(row.day) ?? '',
				focusSeconds: num(row.focus_seconds),
				studySeconds: num(row.study_seconds),
			})),
		}
	},

	/**
	 * Compatibility wrapper for older feature code. Reward state is no longer
	 * mutated directly from the browser; a validated activity RPC drives XP,
	 * streaks and achievements in Postgres.
	 */
	async record(
		userId: string,
		event: XpEvent,
		_delta: Partial<DayStats> = {},
	): Promise<{ xpAwarded: number; unlocked: AchievementDefinition[] }> {
		const before = await gamificationRepository.summary(userId)
		let kind: string | null = null
		let metadata: Record<string, unknown> = {}
		if (event.kind === 'lesson_completed') kind = 'lesson_completed'
		else if (event.kind === 'revision_completed') kind = 'revision_completed'
		else if (event.kind === 'flashcards_completed') kind = 'flashcards_completed'
		else if (event.kind === 'practice_session') {
			kind = 'practice_completed'
			metadata = { attempted: event.questions }
		} else if (event.kind === 'focus') {
			kind = 'focus_completed'
			metadata = { seconds: Math.round(event.minutes * 60) }
		}

		// Tasks are generated by the study_tasks trigger and chapter rewards are
		// intentionally not synthesized from the client without chapter evidence.
		if (!kind) return { xpAwarded: 0, unlocked: [] }

		const { error } = await getSupabase().rpc('log_activity_v1', {
			p_kind: kind,
			p_subject_id: null,
			p_chapter_id: null,
			p_topic_id: null,
			p_lesson_id: null,
			p_exam_key: null,
			p_metadata: metadata,
		})
		if (error) throw error

		const after = await gamificationRepository.summary(userId)
		const newKeys = after.unlocked.filter((key) => !before.unlocked.includes(key))
		return {
			xpAwarded: Math.max(0, after.totalXp - before.totalXp),
			unlocked: ACHIEVEMENTS.filter((item) => newKeys.includes(item.key)),
		}
	},

	definitions: ACHIEVEMENTS,
}